/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package http4ktest

import org.http4k.core.then
import org.http4k.filter.DebuggingFilters
import org.http4k.filter.ServerFilters.CatchLensFailure
import org.http4k.server.Http4kServer
import org.http4k.server.Jetty
import org.http4k.server.asServer

fun server(port: Int): Http4kServer {
    return DebuggingFilters.PrintRequestAndResponse().then(CatchLensFailure).then(appRoutes).asServer(Jetty(port))
}

fun main(args: Array<String>) {
    server(9000).start()

    println("server started")
}
